[project]
name = "mcp_leave_management_tutorial"
version = "0.1.0"
description = "A tutorial MCP server for managing employee leaves, demonstrating basic tool and resource creation."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
]
